services:
  strm-api:
    image: tgszy/strm-helper:latest
    container_name: strm-helper
    restart: unless-stopped
    ports:
      - "35455:35455"                 # ★ 内外端口一致
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - strm-net

  # 前端开发服务（可选，仅开发环境使用）
  # frontend:
  #   image: tgszy/strm-helper:latest
  #   container_name: strm-frontend
  #   restart: unless-stopped
  #   command: frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app/frontend
  #   environment:
  #     - VITE_API_BASE=http://localhost:35455/api
  #   depends_on:
  #     - strm-api
  #   networks:
  #     - strm-net

  redis:
    image: redis:7-alpine
    container_name: strm-redis
    restart: unless-stopped
    networks:
      - strm-net

  worker:
    image: tgszy/strm-helper:latest
    container_name: strm-worker
    restart: unless-stopped
    command: worker
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - strm-net

  beat:
    image: tgszy/strm-helper:latest
    container_name: strm-beat
    restart: unless-stopped
    command: beat
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - strm-net

  flower:
    image: mher/flower:2.0
    container_name: strm-flower
    restart: unless-stopped
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - strm-net

networks:
  strm-net:
    driver: bridge
