version: "3.9"

services:
  strm-api:
    image: tgszy/strm-helper:latest
    container_name: strm-helper
    restart: unless-stopped
    ports:
      - "35455:35455"
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    # 若 /health 未实现，先注释掉下面 6 行
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35455/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - strm-helper-net

  redis:
    image: redis:7-alpine
    container_name: strm-redis
    restart: unless-stopped
    networks:
      - strm-helper-net

  worker:
    image: tgszy/strm-helper:latest
    container_name: strm-worker
    restart: unless-stopped
    command: worker
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - strm-helper-net

  beat:
    image: tgszy/strm-helper:latest
    container_name: strm-beat
    restart: unless-stopped
    command: beat
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - strm-helper-net

  flower:
    image: mher/flower:2.0
    container_name: strm-flower
    restart: unless-stopped
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - strm-helper-net

networks:
  strm-helper-net:
    driver: bridge
