services:
  strm-api:
    image: tgszy/strm-helper:latest
    container_name: strm-api
    restart: unless-stopped
    ports:
      - "35455:35455"                 # ★ 内外端口一致
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    networks:
      - strm-net

  redis:
    image: redis:7-alpine
    container_name: strm-redis
    restart: unless-stopped
    networks:
      - strm-net

  worker:
    image: tgszy/strm-helper:latest
    container_name: strm-worker
    restart: unless-stopped
    command: celery -A backend.celery_app.celery worker -l info -Q default -c 4
    volumes:
      - ./data:/app/data
      - ./media:/media
      - ./strm:/strm
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - strm-net

  flower:
    image: mher/flower:2.0
    container_name: strm-flower
    restart: unless-stopped
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - strm-net

networks:
  strm-net:
    driver: bridge
