[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "strm-helper"
version = "0.2.0"
dependencies = [
    "requests>=2.28",
    "pyyaml>=6.0",
    "pydantic>=2.0",
]

[project.scripts]
strm = "backend.cli:main"
