name: Debug Container (one-shot)

on:
  workflow_dispatch:   # 手动触发

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 拉取最新镜像并执行命令
      - name: Check container files
        run: |
          docker pull tgszy/strm-helper:latest
          docker run --rm tgszy/strm-helper:latest sh -c "
            echo '=== /app/backend/ ===' &&
            ls -l /app/backend/ &&
            echo '=== main.py head ===' &&
            cat /app/backend/main.py | head -20
          "
