name: Docker Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手动触发按钮

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉代码（含 .git 供前端读版本）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 登录 Docker Hub（用你刚才填的密钥）
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 多阶段构建 & 推送（amd64，飞牛 NAS 专用）
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            tgszy/strm-helper:latest
