name: Build & Push Multi-Arch Docker Image

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:          # 手动触发按钮

env:
  IMAGE_NAME: tgszy/strm-helper   # ← 您的 Hub 仓库

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3        # 多架构虚拟化
      - uses: docker/setup-buildx-action@v3      # Buildx 构建器

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 生成版本号
        id: ver
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=sha-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ steps.ver.outputs.tag }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile               # 使用根目录单 Dockerfile
          platforms: linux/amd64   # 按需保留
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha            # GitHub Actions 缓存
          cache-to: type=gha,mode=max
