name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # ====== 前端占位测试 ======
  fe-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --legacy-peer-deps
        working-directory: frontend
      # 占位：避免“missing script”退出 1
      - run: npm run test:unit || echo "no unit tests yet"
        working-directory: frontend

  # ====== 后端占位测试 ======
  be-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      # 占位：有 pytest 就跑，没有就跳过
      - run: pytest backend/tests || echo "no backend tests yet"
        env:
          REDIS_URL: redis://localhost:6379/0
